#ifndef __SYSTEM_DEFINE_H__
#define __SYSTEM_DEFINE_H__

enum SYSTEM_ID
{
	SYSTEM_ID_PLAYER_SYSTEM = 0,
	SYSTEM_ID_SCENE_SYSTEM,
	SYSTEM_ID_MOTION_SYSTEM,
	SYSTEM_ID_CONFIG_SYSTEM,
	SYSTEM_ID_SKILL_SYSTEM,
	SYSTEM_ID_COUNT,
};

#endif // __SYSTEM_DEFINE_H__